export default {
  operatorMap: {
    EQ: '==',
    NEQ: '!=',
    LT: '<',
    LEQ: '<=',
    GT: '>',
    GEQ: '>=',
    NULL: 'is null',
    NOT_NULL: 'is not null',
    LIKE: 'like',
    NOT_LIKE: 'not like',
    BETWEEN: 'between',
    IN: 'in',
    NOT_IN: 'not in',
    BEGIN_WITH: 'begin with',
    NOT_BEGIN_WITH: 'not begin with',
    END_WITH: 'end with',
    NOT_END_WITH: 'not end with',
    TODAY: '今天',
    'BEFORE_DAY.1': '昨天',
    'BEFORE_DAY.2': '前天',
    'NEARLY_DAY.7': '近7天',
    'NEARLY_DAY.30': '近30天',
    'NEARLY_YEAR.1': '近1年',
  },
  operatorList: [
    {
      type: 'TEXT',
      defaultOperator: 'EQ',
      operators: [
        'EQ',
        'NEQ',
        'IN',
        'NOT_IN',
        'LIKE',
        'NOT_LIKE',
        'NULL',
        'BEGIN_WITH',
        'NOT_BEGIN_WITH',
        'END_WITH',
        'NOT_END_WITH',
      ],
    },
    {
      type: 'NUM',
      defaultOperator: 'EQ',
      operators: ['EQ', 'NEQ', 'LT', 'LEQ', 'GT', 'GEQ', 'BETWEEN'],
    },
    {
      type: 'DATE',
      defaultOperator: 'TODAY',
      operators: [
        'TODAY',
        'BEFORE_DAY.1',
        'BEFORE_DAY.2',
        'NEARLY_DAY.7',
        'NEARLY_DAY.30',
        'NEARLY_YEAR.1',
        'LT',
        'LEQ',
        'GT',
        'GEQ',
        'BETWEEN',
      ],
    },
  ],
  operatorsNoInput: [
    'NULL',
    'NOT_NULL',
    'TODAY',
    'BEFORE_DAY.1',
    'BEFORE_DAY.2',
    'NEARLY_DAY.7',
    'NEARLY_DAY.30',
    'NEARLY_YEAR.1',
  ],
};
